import { Geist, Geist_Mono } from "next/font/google";
import "../../../app/globals.css";
import SideNav from "@/app/components/DashBoard/common/SideNav";
import TopNav from "@/app/components/DashBoard/common/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  //   const token = await cookies();
  //   const myToken = token.get("token")?.value;

  //   if (!myToken) {
  //     return redirect("/login");
  //   }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex relative bg-[#f5f5fa]!`}
      >
        <SideNav />

        <div className="">
          <TopNav />
          <div className="mt-28">{children}</div>
        </div>
      </body>
    </html>
  );
}
