import { Geist, Geist_Mono } from "next/font/google";
import "../../../app/globals.css";

import Footer from "@/app/components/common/Footer";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import MainNav from "@/app/components/common/Navbar/MainNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const token = await cookies();
  const myToken = token.get("token")?.value;

  if (!myToken) {
    return redirect("/login");
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MainNav />
        <div className="my-[140px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
